### ISSUE TITLE
Download Results as CSV

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#102]
* Add ability to download specific data for a given search through a UI when clicking “Download CSV”
Example: exclude instructor names in a download
 Add the CSV download feature to all search result pages
* Ensure all downloaded CSVs are correctly formatted and have a ".csv" extension.
* Allow users to download CSV files without authenticating (logging in to GitHub)
* Allow downloading of CSV for personal schedule page
* Generalize CSV download to a web API, allowing direct download through a shareable URL.

**Comment by pconrad** [comment]
Branch name: 't-7pm-c-download-csv'
