### ISSUE TITLE
Change file extension for CSV download to be '.csv'

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#111]
As a user I want the downloaded CSV to have the '.csv' file extension, and to be named appropriately based on the any search of filters applied.

Appears to work perfectly fine when attempting to download with Google Chrome (has .csv extension). Firefox (only one we have tested) doesn't seem to work.

**Comment by SuryaPugal** [comment]
For every filter applied, we should add the name of said filter to the name of the downloaded CSV as a string. Would adding .csv to this string be sufficient for providing the file with the ".csv file extension".
