### ISSUE TITLE
Add Download CSV button to search results

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#112]
As a user I want to be able to download search results as a CSV from the results page.

Acceptance Criteria:
* There is a download button on the search results page
* Download button downloads correctly formatted CSV of the page's results

**Comment by nahpruhtraton** [comment]
Seems like most of the html files are in the path src/main/resources/templates/ , so that should be a starting point for where to add the download button functionality for the website.

**Comment by SuryaPugal** [comment]
Ramon and I were experimenting with the behavior of the button for the instructor search feature of the application.
