### ISSUE TITLE
Document CSV download API

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#115]
Document the design for the download CSV API

Acceptance Criteria:  

* All functionality described
* Will include an example of expected input/output 
* Documentation placed in wiki (or other appropriate location)

**Comment by nahpruhtraton** [comment]
Since README.md for this project is on how to run the program, we'll need to use the wiki part or something else. If we use the wiki provided by github, it may be harder for the average non-CS user to read. Perhaps we should add a functionality/ instructions page to the website itself.

**Comment by SuryaPugal** [comment]
Documentation is now on the wiki.
