### ISSUE TITLE
Allow users to remove courses from a schedule

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#116]
As a user I want to be able to remove courses from my schedule.

Acceptance Criteria
- [x] Click a remove button, and upon removal course no longer appears in your personal schedule page
- [x] If you remove a class, the associated section should also be removed

**Comment by yirenhan** [comment]
In order to accomplish this, we need to modify the html file to add a "remove" button. We would need to connect that button to the java code, which then removes the course and its associated section from your personal schedule.

**Comment by jinpark7898** [comment]
2nd Acceptance Criteria can be worked on only when a lecture can be added to the personal schedule.
