### ISSUE TITLE
Allow adding courses that do not have sections

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#118]
Courses that do not have section cannot currently be added.

- [x] Create the ability to add the lecture itself (without the section).

**Comment by Zonkman** [comment]
It looks like the Course class stores associated lectures as a string instead of some hypothetical Lecture object. This means it's not currently possible to represent a lecture without a section. A Lecture object would also be very helpful to add a lecture by itself.
