### ISSUE TITLE
Create a table that displays final times for a given schedule

### ISSUE THREAD

**Issue by agprice** [ucsb-cs56-w20/ucsb-courses-search#119]
As a user I want to see the final times for my schedule.

Acceptance Criteria
- [ ] Finals times get updated when removing/adding courses

**Comment by jinpark7898** [comment]
I think it needs changes in HTML code of templates/courseschedule/index.html to prepare displaying a new table or a list of final times with new Java file that controls the list of final times of corresponding classes.
