### ISSUE TITLE
As a member of UCSB, I would like to be able to login with my UCSB Connect (Google) account instead of GitHub.

### ISSUE THREAD

**Issue by ryan8xia** [ucsb-cs56-w20/ucsb-courses-search#131]

**Comment by AndrewJGaut** [comment]
At a high level, to do this, we will definitely have to modify lots of Java code (like the [OauthUtils.java file](https://github.com/ucsb-cs56-w20/ucsb-courses-search/blob/master/src/test/java/edu/ucsb/cs56/ucsb_courses_search/OAuthUtils.java)) and some minor changes to the HTML code (e.g., changing the text 'Github login' to 'Google Oauth Login' for the login button in the upper right hand corner).
