### ISSUE TITLE
Perform validation so only UCSB Connect accounts can log in to our website.

### ISSUE THREAD

**Issue by ryan8xia** [ucsb-cs56-w20/ucsb-courses-search#132]

**Comment by AndrewJGaut** [comment]
Acceptance Criterion 1: Users without UCSB Connect accounts cannot login to our website.

**Comment by xitsleena** [comment]
Acceptance Criterion 2: Users with UCSB Connect accounts can login to our website.

**Comment by laineywatlington** [comment]
Acceptance criteria:

**Comment by samhita-h** [comment]
Acceptance Criterion 3: Only users with ucsb email accounts can log into the website

**Comment by ScudBt** [comment]
Acceptance Criterion 3:Users with faked UCSB Connect accounts cannot login to our website.

**Comment by finnderman1** [comment]
I approve!

**Comment by AndrewJGaut** [comment]
Clarification:

Do we want people without UCSB accounts to not be able to log in to the application at all, or do we want them to be able to log in as 'guests' who can't really see things like Personal Schedule (which is reserved for members, admins)?

**Comment by ryan8xia** [comment]
> Clarification:
> 
> Do we want people without UCSB accounts to not be able to log in to the application at all, or do we want them to be able to log in as 'guests' who can't really see things like Personal Schedule (which is reserved for members, admins)?

As a staff we had a discussion about this. I believe @pconrad mentioned that he wanted to restric the entire app to UCSB.edu. The reasoning is that we don't want outside users filling up our database tables.

**Comment by AndrewJGaut** [comment]
OK got it, thanks!

**Comment by ryan8xia** [comment]
We have modified this so that most pages are publicly available, but the my schedule section is restricted to UCSB.edu
