### ISSUE TITLE
As a user, I would like to be able to specify the list of classrooms that appear in a search.

### ISSUE THREAD

**Issue by kerem-signifai** [ucsb-cs56-w20/ucsb-courses-search#135]

**Comment by spenceryzou** [comment]
I think an array of all the classrooms can be put into the backend.
Then a dropdown with all the classrooms from the array can be accessed when using the search bar.

**Comment by ryan8xia** [comment]
In this case, we will probably implement this with an add class room button. This give the user an extra two fields for building and classroom (note they should only be able to search in the same quarter).

**Comment by ryan8xia** [comment]
Acceptance Criteria: As A user, when I click a add button, extra fields drop down that allow me to search for extra classrooms (within the same quarter)
