### ISSUE TITLE
Fix the location of black lines separating courses (the sorting messes it up)

### ISSUE THREAD

**Issue by kerem-signifai** [ucsb-cs56-w20/ucsb-courses-search#136]

**Comment by BrandonBai18** [comment]
> Link to pull request： <https://github.com/ucsb-cs56-w20/TEAM-t-6pm-a/pull/8|https://github.com/ucsb-cs56-w20/TEAM-t-6pm-a/pull/8>
<sub>[View in Slack](https://ucsb-cs56-w20.slack.com/archives/CS1Q790LB/p1582225556027800)</sub>

**Comment by BrandonBai18** [comment]
> Link to pull request： <https://github.com/ucsb-cs56-w20/TEAM-t-6pm-a/pull/8|https://github.com/ucsb-cs56-w20/TEAM-t-6pm-a/pull/8>
<sub>[View in Slack](https://ucsb-cs56-w20.slack.com/archives/CS1Q790LB/p1582225556027800)</sub>

**Comment by BrandonBai18** [comment]
in src/main/java/edu/ucsb/cs56/ucsb_courses_search find the right files implementing sorting method. For now, sorting makes no sense. Im going to fix the method by sorting by name or course numbers. Also, For now, different course can go under between two black lines. About to fix it by put same courses or with the same numbers between two black lines.

**Comment by pconrad** [comment]
I spoke with @samhita-h about this issue.

Currently on the csdept page, some info for sections is not showing up.

This is because we refactored and are using the `generic_results_table.html` as the view.

And in that file, there is this code:

```th:text="${r.rowType}=="PRIMARY' ? ${r.course.courseId} :  ''
