### ISSUE TITLE
As a user, I would like the ability to autocomplete building and classroom names.

### ISSUE THREAD

**Issue by kerem-signifai** [ucsb-cs56-w20/ucsb-courses-search#137]

**Comment by tristanhernandez** [comment]
I have a few questions about this, and I feel could be unnecessary.  I feel that for it to work, it should first attempt to autocomplete for building name, and then to fill in the number after the room name has been decided.  To do this, we would need to take names from a database (possibly an arraylist) and select the buildings containing the first letters that had been inputted by the user, and then for each building, there is an arraylist (possibly a map that contains keys) of appropriate room names from the building.  We would also do that first step for each room.  We would also need a search bar for classrooms first and foremost, as it is not there yet.  We should also consider the autocomplete having full names and abbreviated names.
