### ISSUE TITLE
The title is currently "Getting Started: Serving Web Content". This should be changed.

### ISSUE THREAD

**Issue by ryan8xia** [ucsb-cs56-w20/ucsb-courses-search#141]

**Comment by jackkilgore** [comment]
There is a clickable button that opens a popup menu.

**Comment by kgusdorf** [comment]
Acceptance Criteria:
The title is UCSB Course Search

**Comment by kgusdorf** [comment]
To reach the Acceptance Criteria, the title in the page index HTML code should be modified. It is currently <title>Getting Started: Serving Web Content</title>.
