### ISSUE TITLE
As a user, I would like to have a button next to a course result that displays more info about a course.

### ISSUE THREAD

**Issue by ryan8xia** [ucsb-cs56-w20/ucsb-courses-search#142]

**Comment by jackkilgore** [comment]
Acceptance Criteria:
There is a clickable button that opens a popup menu.

**Comment by jackkilgore** [comment]
Ideas for Completing this Story:

- Under source/main/resources/templates:
     We will need a new html file that will display course details when a button is pressed. 
          - Lets call it courseDetails.html
     The button needs to be added to the searchResults.html. This will redirect us to our new html file.

- We will also need to make a new controller that will be able to retrieve information from our APIs and display it courseDetails.html

**Comment by jackkilgore** [comment]
More in depth accceptance criteria: 

On the front page course search results, the department search results, and the instructor search results, there is clickable button per course. This button will open up a modal.
