### ISSUE TITLE
As a user, I want the course information popup to include the final exam time.

### ISSUE THREAD

**Issue by ryan8xia** [ucsb-cs56-w20/ucsb-courses-search#144]

**Comment by CJUCSB** [comment]
Acceptance Criteria: Popup will include the exam time and potentially location after popup occurs.

**Comment by CJUCSB** [comment]
To implement, I would add java code to read the data from wherever the web app is getting course information, parse it to get the string of the exam time, then add an HTML element that will be changed to contain the string value that the java code extracted.
