### ISSUE TITLE
As a user, I would like to see my schedule in a “Weekly View” format, similar to GOLD, so we can easily see what our week looks like.

### ISSUE THREAD

**Issue by andrewhlu** [ucsb-cs56-w20/ucsb-courses-search#148]
Acceptance Criteria

- Table with Weekdays on the top, Time left column

- Classes added to the table correspond to the time and day of the class and shows location of class

-  Displayed on the same page as list view

**Comment by armaans13** [comment]
To see classes in a weekly view, we could use HTML formatting to have different rows and columns for the weekdays and times. Based on the results we pull from UCSB's API on the information of each class we add to our schedule, we can import that class' information to the correct day and time, and then also display it with location information.

**Comment by lanch17** [comment]
branch: t-7pm-a-weeklyview
