### ISSUE TITLE
As a user, I would like to be able to search across multiple quarters, so I can know which GE courses to potentially take in the future.

### ISSUE THREAD

**Issue by btk5h** [ucsb-cs56-w20/ucsb-courses-search#149]
Acceptance criteria: I should be able to enter the GE areas that I'm interested in and the range of quarters I want to search through. The list of the courses should be outputted following the front-end templates (list view).

**Comment by KH07** [comment]
Code change: 

Model: New file SearchByGEArea.java in src/mian/java/edu/ucsb/cs56/ucsb_courses_search/model/search

View: New directory byGEArea src/main/resources/templates/search

Controller: New file SearchByGEAreaController.java in src/mian/java/edu/ucsb/cs56/ucsb_courses_search/controller

**Comment by tiletv** [comment]
I should change the html for display to let the users see the layout for different quarters.

**Comment by jaoyama73** [comment]
The display of courses within each quarter column will exclude sections' information. (Since the main purpose of the multi-quarter search is for general course planning instead of section time arranging, so it would easier to see the result without the distraction of section times)
