### ISSUE TITLE
When adding a course, I would like to select an active schedule which all courses will be added to.

### ISSUE THREAD

**Issue by vincentktieu-ucsb** [ucsb-cs56-w20/ucsb-courses-search#166]
We would need an interface to select a schedule from the list of many schedules. A start would be to change the add input button to a dropdown menu to select schedules by name. Then the selected schedule would need to be updated accordingly in the database/form.

Additional improvements could be to add 'tick' boxes to the dropdown of schedules followed by a submit form button. This would allow for schedules to be added into multiple schedules.

**Comment by Neemers** [comment]
Working to add a drop down menu of available courses when the "add" button is pressed.
