### ISSUE TITLE
DRY up the selectors for quarters

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/ucsb-courses-search#178]
Lots of forms have a drop down list of quarters.  Right now, if you want to update those to include a future quarter e.g. SUMMER 2020, FALL 2020, WINTER 2021, you have to hand edit each of those menus.

We want to DRY that up.

User Story: As a developer, I can generate a list of quarters rather than having to hard code an HTML selector for a  list of quarters in each of my forms that needs a list of quarters.

* [x] Add app.start_quarter and app.end_quarter as properties in application.properties  in format, e.g. F01 or S20.
* [x] Add a QuarterListService that provides access to the app
* [x] Implement QuarterListService into every part of the app that needs it

**Comment by pconrad** [comment]
See the file: /src/main/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/Quarter.java

**Comment by pconrad** [comment]
Also: src/test/java/edu/ucsb/cs56/ucsbapi/academics/curriculums/utilities/TestQuarter.java

And: if you look in: `/src/main/resources/templates/search/bycourse/fragments/form.html`
the code starting at this line shows how a List<Quarter> can be used:

[See code at this link](https://github.com/ucsb-cs56-w20/ucsb-courses-search/blob/ac5c66f664af026dbba86cc8f3d1408c15a9b24d/src/main/resources/templates/search/bycourse/fragments/form.html#L8)

The list of quarters being iterated over is put into the model in the controller.  The idea is to get the start and end from the service object, and do that everywhere in the app.

```

**Comment by alex-shortt** [comment]
New branch created: `w-7pm-d-quarter-selector-service`

**Comment by alex-shortt** [comment]
TODO:
* [ ] Maybe make `QuarterListService` static
