### ISSUE TITLE
Adding a course that does not have a final time will create an error when viewing the schedule

### ISSUE THREAD

**Issue by andrewhlu** [ucsb-cs56-w20/ucsb-courses-search#302]
Some courses, especially lab courses, do not have a final time. Instead, GOLD will display "Contact Professor for Final Exam Information". When you add such a class to your schedule, and then go to view that schedule later, the JSON processor does not know how to handle this situation, and the app will return a "Whitelabel Error Page" when trying to access the schedule. 

This **permanently** prevents the user from viewing their schedule until this is fixed.

Courses tested: ECE 10BL, ECE 10CL, Physics 4L.

**Comment by agprice** [comment]
Fixed by: https://github.com/ucsb-cs56-w20/ucsb-courses-search/pull/303
