### ISSUE TITLE
Create template for Basic Search by Instructor with form

### ISSUE THREAD

**Issue by ganeshsankaran** [ucsb-cs56-w20/ucsb-courses-search#36]
Acceptance criteria for this issue include

- [x] HTML template(s) under "instructor" folder

- [x] Template contains a search form with an instructor form that does nothing upon submit

- [x] Remap "/instructor" to "/instructor/search" so that there is room for multiple "/instructor" routes

**Comment by andrewhlu** [comment]
Doing some cleanup of really old issues. This issue has already been solved.
