### ISSUE TITLE
Create template for Multiquarter Search with form

### ISSUE THREAD

**Issue by ganeshsankaran** [ucsb-cs56-w20/ucsb-courses-search#37]
Acceptance criteria for this issue include

- [x] HTML template(s) under "instructor" folder

- [x] Template contains a search form with an instructor and quarter range field that does nothing upon submit

- [x] Map "/instructor/multiqtrsearch" to this template

**Comment by andrewhlu** [comment]
Doing some cleanup of really old issues. This issue has already been solved.
