### ISSUE TITLE
Fix Typos in InstructorSearchController.java

### ISSUE THREAD

**Issue by ganeshsankaran** [ucsb-cs56-w20/ucsb-courses-search#74]
Currently, there are multiple instances of the word "specific" being spelled wrong, such as in <code>public String specifc(Model model)</code> and <code>InsSearchSpecific insSearchSpecic</code>. Using these poorly named methods and variables may be confusing as the complexity of the controller grows. Therefore, these should be renamed properly!

**Comment by andrewhlu** [comment]
Doing some cleanup of old issues. This issue seems to have already been solved.
