### ISSUE TITLE
As a user, I can see a menu bar called CS Dept and an item on that menu called Dept Controlled Classrooms  that allows me to search all courses scheduled for a given quarter in dept controlled classrooms so that I can check it against the Google Calendar.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/ucsb-courses-search#82]
Orignally this is just the course list, with courses that are not [Phelps 2510, 3535, 3536, HFH 1132, 1152] filtered out.

Eventually, it might be nice to sort first by classroom, then by time.. but that's for later.

**Comment by andrewhlu** [comment]
Addressed in PRs #83 and #84.
